<a href="https://colab.research.google.com/github/dharani756/DS-lab/blob/main/ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [11]:
file=pd.read_csv("/content/sample_data/insurance.csv")
file

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [32]:
import matplotlib.pyplot as plt

In [33]:
X = file[['age', 'bmi', 'children']]
y = file['charges']

In [34]:
from sklearn.linear_model import LinearRegression

In [35]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [36]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [29]:
y_pred = model.predict(X_test)
y_pred

array([13305.28945949, 11801.95170145, 16941.71437111, 14278.42206855,
        8680.25439362, 16202.22349193,  5555.8901083 , 20602.58565492,
        5806.95206068, 15919.03165614, 10299.48549201, 14221.13480456,
       10676.8197114 , 19794.64417995, 20721.14505796, 18319.57207031,
       20003.52486079, 16989.16491869, 13918.10991054, 12305.80129754,
       10155.63429188, 15330.37731182,  8175.30663033, 11961.94421188,
       15950.43401031, 16659.25006455, 18787.72664854, 11630.42705085,
       14220.19351839,  7868.1762212 , 14697.87471015, 17037.49024392,
       10101.76722818,  8821.1844745 , 10150.74943027, 17039.37281627,
        7851.03169019, 13870.41119463, 13940.42279767, 14085.77995875,
       10392.4393359 ,  9716.19171103, 18700.25675242, 15364.53701599,
       14169.23745665, 16605.24949913, 10815.87502296,  9162.47641738,
       17012.91908784, 14604.73646207, 19848.64291578,  8175.39974722,
       17035.11042013,  6534.38328069, 17682.11992809, 16712.90245652,
        8962.56181915, 13838.94599111, 17681.80616603, 16627.84771037,
       18353.73177448, 15955.29640741, 21029.74518705, 12579.89769286,
       15618.10906483,  9241.86189678,  9307.54825435, 15820.56128268,
        7443.45613316, 11860.62245675, 15141.87006988, 15892.9898653 ,
       15550.6350814 , 14360.97360647, 16801.94116293, 11768.73145387,
       12356.28946057, 14765.38219017, 12151.89182104, 14042.71519173,
        9369.41764997, 16437.08036988, 11971.87495997, 12267.28608035,
       16768.85027321, 15492.18588607, 12681.37724382, 16911.56706516,
       14694.20957058, 19429.7843017 , 21350.22745935, 15647.78572769,
       13499.37790994, 11035.22085911, 13606.21802424, 14755.98079067,
       11119.83937357,  9259.79083294, 10051.9946475 , 10529.64557172,
       10503.91754293,  7677.00291657, 16307.49388114, 19925.95636001,
       15206.4270779 , 10112.1401814 , 14916.62834837, 12525.14713369,
        4987.98075563, 13745.92746828,  9072.25331511, 15642.05635599,
       18010.62285298, 12554.64030716, 15487.29596582,  9822.81026536,
       16626.74954317, 13370.38270434, 13407.86626285,  8611.46159782,
       12996.46960003, 15420.38574236, 19237.32751088, 11092.92097549,
        9110.57815468, 15041.6749199 , 15777.25340597, 15171.70361377,
       18600.18913072, 12881.98818894, 10556.81994115, 14698.72287943,
       14647.29525981, 16534.42505298, 13387.74788052, 19794.39326724,
       12875.43634152, 13119.85424438, 16534.58193401, 12275.1833485 ,
       10760.49693968, 16407.24682599, 11388.26741693, 18953.29439403,
        7951.78968535, 14329.50657336, 11413.61791952, 10392.53659663,
       18916.84523858, 12303.67055687, 19516.15694542,  8300.91604704,
       11522.4034555 , 12681.19101004, 16309.56177247, 12906.83869569,
       18235.95677658, 14577.37494406,  9075.57533987, 14163.22001645,
       18384.28687417,  7191.92353769, 17640.87305448,  7101.66510924,
       11511.46168366, 16631.10688579, 20313.72638196, 16816.57559749,
       14572.86255001,  9466.6329752 , 12338.01649481, 13851.10657019,
       16661.60327998,  9904.135193  ,  7741.31175627, 13261.85313972,
        7278.35994555, 21458.00703022,  7973.81816318, 14165.59984025,
       17004.98972255,  4666.87095921, 11321.79068078, 13145.96071416,
        9452.52605963, 10257.43174874, 10693.42983519,  9706.69536504,
       19876.00443379, 15207.36836408, 12973.15257738,  7544.27880726,
        6439.07805096, 13910.43328755, 20468.35741426, 16468.70428402,
        6781.65348002, 16522.91952117,  6597.5017511 , 13424.22547393,
        7006.51676054, 14450.41736224, 16320.71913083,  8259.89073339,
        7776.44301415,  8064.42476508, 13693.30947937,  7496.95164411,
       17816.25596666,  6873.72888709, 14678.06826028, 14994.38125334,
       21131.82290937,  8611.05471887, 12133.3991249 ,  9783.10193449,
       11121.34350492, 17840.91518099, 15276.34647886, 13536.14174225,
       10384.13933264, 16723.93734524, 19196.43064031, 17144.20282994,
        9405.64616025, 10587.34568809,  4919.72236705,  8238.42510074,
       15679.65963975, 20727.59872985, 10759.52813035, 11136.85454671,
        9582.14878935, 12609.76656293, 11452.29001774, 16940.74556178,
       11004.44602905, 14481.88439535, 17690.83278373,  9957.10227015,
       13218.352141  , 13203.15577606, 10856.90033661, 10124.1732322 ,
        6439.54869404,  9941.52563463, 10324.77820389, 11973.59973649,
       23706.92053096,  3883.25064242,  8130.30241507, 16128.0701328 ,
        8633.99513012, 13850.00748819,  9211.71459083, 10670.803186  ,
       16728.0712983 , 11451.3221232 , 12178.62307054, 12545.01734769,
       13932.21176746, 14354.32772736,  9526.11565879, 19446.67792001,
       15711.84548427, 12143.74272538, 21552.59253374, 17064.94396402])

In [30]:
from sklearn.metrics import mean_squared_error, r2_score

In [31]:
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MSE: 131201335.64669803
R2 Score: 0.15489592484270776

In [37]:
import pandas as pd

In [40]:
file = pd.read_csv("/content/sample_data/breast-cancer.csv")
file

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [41]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [42]:
input = file[["radius_mean",	"texture_mean",	"perimeter_mean"]]
output= file["diagnosis"]

In [43]:
from sklearn.linear_model import LogisticRegression

In [44]:
model=LogisticRegression()

In [45]:
model.fit(input,output)

LogisticRegression()

In [49]:
model.predict([[17.99,10.38,122.8]])[0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

'M'